apiVersion: v1
kind: Service
metadata:
  name: grade-service
  namespace: grading-system
  labels:
    app: grade-service
spec:
  type: ClusterIP
  selector:
    app: grade-service
  ports:
  - name: http
    port: 5002
    targetPort: 5002
    protocol: TCP

